---
- name: Enable and disable services
  hosts: all
  roles:
   - servicemgt
  tasks:
   - name: Enable services
     ansible.builtin.service:
      name: "{{ item }}"
      enabled: yes
      state: started
     with_items:
      - "{{ enable_services }}"

   - name: Disable services
     ansible.builtin.service:
      name: "{{ item }}"
      enabled: no
      state: stopped
     with_items:
      - "{{ disable_services }}"
